export const OLD_WOMAN_PROMPT = `elderly japanese woman character reference sheet,
short and slightly stooped posture,
kind wrinkled face,
gray hair in low bun,
wearing indigo work kimono and patterned apron,
traditional wooden sandals,
gentle grandmother personality,
multiple poses (standing, washing clothes, smiling, surprised),
children's book character reference sheet,
watercolor and ink illustration,
soft pastel palette,
storybook style,
clean white background,
multiple poses and expressions,
textured watercolor paper`;

export const OLD_MAN_PROMPT = `elderly japanese farmer character reference sheet,
thin but sturdy build,
white beard and mustache,
friendly weathered face,
simple brown kimono with rope belt,
straw hat,
walking stick,
multiple poses (standing, laughing, surprised, carrying firewood),
children's book character reference sheet,
watercolor and ink illustration,
soft pastel palette,
storybook style,
clean white background,
multiple poses and expressions,
textured watercolor paper`;

export const DOG_PROMPT = `friendly japanese village dog character reference sheet,
medium sized dog,
white fur with brown patches,
curled tail,
alert triangular ears,
loyal and brave personality,
multiple poses (sitting, running, barking, happy tail wagging),
children's book character reference sheet,
watercolor and ink illustration,
soft pastel palette,
storybook style,
clean white background,
multiple poses and expressions,
textured watercolor paper`;

export const MONKEY_PROMPT = `playful japanese macaque monkey character reference sheet,
brown fur,
pale expressive face,
long tail,
clever mischievous personality,
multiple poses (climbing tree, hanging upside down, laughing, thinking),
children's book character reference sheet,
watercolor and ink illustration,
soft pastel palette,
storybook style,
clean white background,
multiple poses and expressions,
textured watercolor paper`;

export const PHEASANT_PROMPT = `japanese green pheasant character reference sheet,
long elegant tail feathers,
metallic green and bronze plumage,
red facial patch,
sharp intelligent eyes,
multiple poses (standing, wings open, flying, perched),
children's book character reference sheet,
watercolor and ink illustration,
soft pastel palette,
storybook style,
clean white background,
multiple poses and expressions,
textured watercolor paper`;

export const ONI_PROMPT = `friendly cartoon japanese oni ogre character reference sheet,
large muscular body,
red blue and green skin variations,
small horns on forehead,
wild hair,
tiger skin loincloth,
holding wooden kanabo club,
expressions ranging from angry to embarrassed,
multiple poses (roaring, running, surrendering),
children's book character reference sheet,
watercolor and ink illustration,
soft pastel palette,
storybook style,
clean white background,
multiple poses and expressions,
textured watercolor paper`;

export const VILLAGE_PROMPT = `storybook environment reference sheet, traditional small Japanese countryside house, wooden structure, thatched roof, sliding paper doors, stone path entrance, small garden and bamboo fence, shown from multiple angles: front view, three-quarter view, side view, wide landscape context, clean white background, children's picture book illustration, watercolor and ink, soft pastel palette, storybook style, textured watercolor paper`;

export const FOREST_PROMPT = `japanese bamboo and pine forest environment reference sheet,
winding dirt path,
bamboo groves,
pine trees,
mossy stones,
sunlight filtering through leaves,
multiple views (forest path, bamboo grove, tree canopy),
children's book environment reference sheet,
watercolor and ink illustration,
soft pastel palette,
storybook style,
clean white background,
textured watercolor paper`;

export const ISLAND_PROMPT = `rocky japanese folklore island environment reference sheet,
dark stone fortress,
steep cliffs,
rough ocean waves,
wooden gates,
treasure courtyard,
multiple views (island landscape, fortress exterior, courtyard),
children's book environment reference sheet,
watercolor and ink illustration,
soft pastel palette,
storybook style,
clean white background,
textured watercolor paper`;

export const BAG_PROMPT = `storybook prop reference sheet,

small traditional Japanese children's travel bag,
indigo cotton sling satchel with simple sashiko stitching pattern,
soft fabric rectangular pouch with flap closure,
single cloth strap worn across the body,

designed for a young traveler in a folktale,

shown in multiple views:
front view,
side view,
back view,
worn cross-body,
resting on the ground,

clean white background,

children's picture book illustration,
watercolor and ink,
soft pastel palette,
storybook style,
textured watercolor paper`;
