import type { TextPageTemplate } from "@/lib/text-pages/types";

export const momotaroTextPageTemplates: readonly TextPageTemplate[] = [
  // Populated via the admin text-page editor.
  // Copy the generated template config and paste entries here.
  {
    templateId: "1-river-introduction-text",
    imageKey: "momotaro/text-pages/1-river-introduction-text.jpeg",
    textBox: { xPct: 0.3002, yPct: 0.2249, wPct: 0.608, hPct: 0.5927 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 34,
      maxSize: 34,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "2-peach-appears-text",
    imageKey: "momotaro/text-pages/2-peach-appears-text.jpeg",
    textBox: { xPct: 0.1412, yPct: 0.2451, wPct: 0.6993, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 34,
      maxSize: 34,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "3-carry-peach-text",
    imageKey: "momotaro/text-pages/3-carry-peach-text.jpeg",
    textBox: { xPct: 0.1765, yPct: 0.3198, wPct: 0.6664, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 34,
      maxSize: 34,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "4-examine-peach-text",
    imageKey: "momotaro/text-pages/4-examine-peach-text.jpeg",
    textBox: { xPct: 0.1899, yPct: 0.3084, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 30,
      maxSize: 30,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "5-peach-opens-b-text",
    imageKey: "momotaro/text-pages/5-peach-opens-b-text.jpeg",
    textBox: { xPct: 0.1764, yPct: 0.3092, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 34,
      maxSize: 34,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "6-couple-hold-child-text",
    imageKey: "momotaro/text-pages/6-couple-hold-child-text.jpeg",
    textBox: { xPct: 0.1485, yPct: 0.3087, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 34,
      maxSize: 34,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "7-getting-strong-text",
    imageKey: "momotaro/text-pages/7-getting-strong-text.jpeg",
    textBox: { xPct: 0.2156, yPct: 0.2887, wPct: 0.6721, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "8-learning-about-ogres-text",
    imageKey: "momotaro/text-pages/8-learning-about-ogres-text.jpeg",
    textBox: { xPct: 0.3026, yPct: 0.3918, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 37,
      maxSize: 37,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "9-declaring-quest-text",
    imageKey: "momotaro/text-pages/9-declaring-quest-text.jpeg",
    textBox: { xPct: 0.2335, yPct: 0.135, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "10-preparing-dumplings-text",
    imageKey: "momotaro/text-pages/10-preparing-dumplings-text.jpeg",
    textBox: { xPct: 0.1391, yPct: 0.1861, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "11-leaving-home-text",
    imageKey: "momotaro/text-pages/11-leaving-home-text.jpeg",
    textBox: { xPct: 0.113, yPct: 0.3426, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "12-meeting-the-dog-text",
    imageKey: "momotaro/text-pages/12-meeting-the-dog-text.jpeg",
    textBox: { xPct: 0.2011, yPct: 0.3303, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "13-sharing-the-dumpling-text",
    imageKey: "momotaro/text-pages/13-sharing-the-dumpling-text.jpeg",
    textBox: { xPct: 0.301, yPct: 0.24, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "14-monkey-joins-text",
    imageKey: "momotaro/text-pages/14-monkey-joins-text.jpeg",
    textBox: { xPct: 0.1308, yPct: 0.5003, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "15-monkey-get-dumpling-text",
    imageKey: "momotaro/text-pages/15-monkey-get-dumpling-text.jpeg",
    textBox: { xPct: 0.2033, yPct: 0.2394, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "16-phaesant-joins-text",
    imageKey: "momotaro/text-pages/16-phaesant-joins-text.jpeg",
    textBox: { xPct: 0.0875, yPct: 0.1705, wPct: 0.6355, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "17-phaesant-gets-dumpling-text",
    imageKey: "momotaro/text-pages/17-phaesant-gets-dumpling-text.jpeg",
    textBox: { xPct: 0.0704, yPct: 0.27, wPct: 0.6191, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "18-looking-at-island-b-text",
    imageKey: "momotaro/text-pages/18-looking-at-island-b-text.jpeg",
    textBox: { xPct: 0.1238, yPct: 0.3756, wPct: 0.7666, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "19-boat-journey-text",
    imageKey: "momotaro/text-pages/19-boat-journey-text.jpeg",
    textBox: { xPct: 0.0715, yPct: 0.1827, wPct: 0.7666, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "20-ogre-fortress-b-text",
    imageKey: "momotaro/text-pages/20-ogre-fortress-b-text.jpeg",
    textBox: { xPct: 0.0297, yPct: 0.3179, wPct: 0.5776, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "21-ogre-infiltration-c-text",
    imageKey: "momotaro/text-pages/21-ogre-infiltration-c-text.jpeg",
    textBox: { xPct: 0.0882, yPct: 0.5632, wPct: 0.765, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "22-battle-scene-text",
    imageKey: "momotaro/text-pages/22-battle-scene-text.jpeg",
    textBox: { xPct: 0.0717, yPct: 0.2747, wPct: 0.8781, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "23-ogres-surrender-text",
    imageKey: "momotaro/text-pages/23-ogres-surrender-text.jpeg",
    textBox: { xPct: 0.0298, yPct: 0.2879, wPct: 0.8781, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "24-take-treasure-text",
    imageKey: "momotaro/text-pages/24-take-treasure-text.jpeg",
    textBox: { xPct: 0.0477, yPct: 0.2688, wPct: 0.8781, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "25-saying-goodbye-text",
    imageKey: "momotaro/text-pages/25-saying-goodbye-text.jpeg",
    textBox: { xPct: 0.0477, yPct: 0.322, wPct: 0.8781, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "26-celebration-text",
    imageKey: "momotaro/text-pages/26-celebration-text.jpeg",
    textBox: { xPct: 0.0859, yPct: 0.3567, wPct: 0.8781, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
  {
    templateId: "27-peaceful-ending-b-text",
    imageKey: "momotaro/text-pages/27-peaceful-ending-b-text.jpeg",
    textBox: { xPct: 0.0653, yPct: 0.3372, wPct: 0.8781, hPct: 0.3998 },
    align: "left",
    valign: "center",
    font: {
      family: "serif",
      minSize: 36,
      maxSize: 36,
      lineHeight: 1.4,
      color: "#2d2520",
    },
    maxLines: 10,
  },
];
